### ISSUE TITLE
[FEATURE REQUEST] Make raised hands GM dismissable

### ISSUE THREAD

**Issue by mech-tools** [cswendrowski/FoundryVTT-Raise-My-Hand#6]
Hello,

Thx for that module!
Can you make it so the "raised hand" icon is more visible on the screen.
Right, that is a small yellow icon in the bottom left corner of the window. Not really visible.

Maybe some kind of snack bar (notification like) that appears up top. This way no one can miss it.
Also, a way for the gm to dismiss the notification.

**Comment by cswendrowski** [comment]
> Can you make it so the "raised hand" icon is more visible on the screen.

I don't plan on changing the current design, but you should be able to easily resize it via https://github.com/cswendrowski/FoundryVTT-Custom-CSS

> Maybe some kind of snack bar (notification like) that appears up top. This way no one can miss it.

There is a setting in the module to display a UI notification

> Also, a way for the gm to dismiss the notification.

This is a good idea, I'll reframe this issue into this part
